In [96]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MaxAbsScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score
from sklearn.metrics import f1_score
import pickle

In [97]:
scaler = MaxAbsScaler()

In [98]:
train = pd.read_csv('train.csv')

In [99]:
test = pd.read_csv('test.csv')

In [100]:
train.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        1           0          0              0             7933   
1       0        0           1          0              0             2600   
2       1        1           2          1              0             1993   
3       1        1           0          0              0             1828   
4       1        0           0          1              0             3598   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0         275               360               1   
1                  0         160               360               1   
2               1625         113               180               1   
3               1330         100               360               0   
4               1287         100               360               1   

   Property_Area  Loan_Status  
0              2            0  
1              2            0  
2              1            1  
3              2            0  
4              0            0

In [101]:
train_y = train.iloc[:,-1]

In [102]:
train_x = train.drop('Loan_Status',axis=1)

In [103]:
test_y = test.iloc[:,-1]

In [104]:
test_x = test.drop('Loan_Status',axis=1)

In [105]:
x = pd.concat([train_x,test_x],axis=0)
y = pd.concat([train_y,test_y],axis=0)

In [106]:
train_x = scaler.fit_transform(train_x)

In [107]:
test_x = scaler.fit_transform(test_x)

# DecisionTree

In [108]:
def decisionTree(train_x,test_x,train_y,test_y):
    dt = DecisionTreeClassifier()
    dt.fit(train_x,train_y)
    y_pred = dt.predict(test_x)
    print("**** Decision Tree Classifier ****")
    print('Confusion Matrix')
    print(confusion_matrix(test_y,y_pred))
    print('Classification Report')
    print(classification_report(test_y,y_pred))

# RandomForest

In [109]:
def randomForest(train_x,test_x,train_y,test_y):
    rf = RandomForestClassifier()
    rf.fit(train_x,train_y)
    y_pred = rf.predict(test_x)
    print("**** Random Forest Classifier ****")
    print('Confusion Matrix')
    print(confusion_matrix(test_y,y_pred))
    print('Classification Report')
    print(classification_report(test_y,y_pred))

# Knn

In [110]:
def knn(train_x,test_x,train_y,test_y):
    knn = KNeighborsClassifier()
    knn.fit(train_x,train_y)
    y_pred = knn.predict(test_x)
    print("**** KNeighbour Classifier ****")
    print('Confusion Matrix')
    print(confusion_matrix(test_y,y_pred))
    print('Classification Report')
    print(classification_report(test_y,y_pred))

# xgboost

In [111]:
def xgboost(train_x,test_x,train_y,test_y):
    xg = GradientBoostingClassifier()
    xg.fit(train_x,train_y)
    y_pred = xg.predict(test_x)
    print("**** Gradient Boosting Classifier ****")
    print('Confusion Matrix')
    print(confusion_matrix(test_y,y_pred))
    print('Classification Report')
    print(classification_report(test_y,y_pred))

# Comparing The Models

In [112]:
decisionTree(train_x,test_x,train_y,test_y)

**** Decision Tree Classifier ****
Confusion Matrix
[[52 42]
 [48 87]]
Classification Report
              precision    recall  f1-score   support

           0       0.52      0.55      0.54        94
           1       0.67      0.64      0.66       135

    accuracy                           0.61       229
   macro avg       0.60      0.60      0.60       229
weighted avg       0.61      0.61      0.61       229



In [113]:
randomForest(train_x,test_x,train_y,test_y)

**** Random Forest Classifier ****
Confusion Matrix
[[ 69  25]
 [ 29 106]]
Classification Report
              precision    recall  f1-score   support

           0       0.70      0.73      0.72        94
           1       0.81      0.79      0.80       135

    accuracy                           0.76       229
   macro avg       0.76      0.76      0.76       229
weighted avg       0.77      0.76      0.76       229



In [114]:
knn(train_x,test_x,train_y,test_y)

**** KNeighbour Classifier ****
Confusion Matrix
[[ 62  32]
 [ 25 110]]
Classification Report
              precision    recall  f1-score   support

           0       0.71      0.66      0.69        94
           1       0.77      0.81      0.79       135

    accuracy                           0.75       229
   macro avg       0.74      0.74      0.74       229
weighted avg       0.75      0.75      0.75       229



In [115]:
xgboost(train_x,test_x,train_y,test_y)

**** Gradient Boosting Classifier ****
Confusion Matrix
[[ 65  29]
 [ 35 100]]
Classification Report
              precision    recall  f1-score   support

           0       0.65      0.69      0.67        94
           1       0.78      0.74      0.76       135

    accuracy                           0.72       229
   macro avg       0.71      0.72      0.71       229
weighted avg       0.72      0.72      0.72       229



In [116]:
rf = RandomForestClassifier()
rf.fit(train_x,train_y)
ypred = rf.predict(test_x)

In [117]:
f1_score(ypred,test_y,average='weighted')

0.7742005478857578

In [118]:
cv = cross_val_score(rf,x,y,cv=5)

In [119]:
np.mean(cv)

0.8164946303826504

In [120]:
import joblib
joblib.dump(rf,'model.pkl')

['model.pkl']

In [121]:
!tar -zcvf model.tgz "model.pkl"

a model.pkl


 Install watson-machine-learning-client module

In [122]:
!pip install ibm-watson-machine-learning

Import the required libraries

In [123]:
from ibm_watson_machine_learning import APIClient

Get credentials

In [124]:
wml_credentials = {
    "url": "https://us-south.ml.cloud.ibm.com",
    "apikey": "BfkRcHp3hwoDe60vOFQ5AwdQQOK6ZK28dj6uDbzRsKqN"
}

client = APIClient(wml_credentials)

## Store the model in deployment spaces

In [125]:
# function to store the model in deployment space
def guid_from_space_name(client, space_name):
    space = client.spaces.get_details()
    return (
        next(item for item in space["resources"] if item["entity"]["name"] == space_name)["metadata"]["id"]
    )

In [126]:
space_uid = guid_from_space_name(client, "space")
print("Space UID - " + space_uid)

Space UID - 9aaafe72-8656-4fb6-8c50-b0ce72cfd99b


##  Make the deployment space default

In [127]:
client.set.default_space(space_uid)

'SUCCESS'

In [128]:
client.software_specifications.list()

-----------------------------  ------------------------------------  ----
NAME                           ASSET_ID                              TYPE
default_py3.6                  0062b8c9-8b7d-44a0-a9b9-46c416adcbd9  base
kernel-spark3.2-scala2.12      020d69ce-7ac1-5e68-ac1a-31189867356a  base
pytorch-onnx_1.3-py3.7-edt     069ea134-3346-5748-b513-49120e15d288  base
scikit-learn_0.20-py3.6        09c5a1d0-9c1e-4473-a344-eb7b665ff687  base
spark-mllib_3.0-scala_2.12     09f4cff0-90a7-5899-b9ed-1ef348aebdee  base
pytorch-onnx_rt22.1-py3.9      0b848dd4-e681-5599-be41-b5f6fccc6471  base
ai-function_0.1-py3.6          0cdb0f1e-5376-4f4d-92dd-da3b69aa9bda  base
shiny-r3.6                     0e6e79df-875e-4f24-8ae9-62dcc2148306  base
tensorflow_2.4-py3.7-horovod   1092590a-307d-563d-9b62-4eb7d64b3f22  base
pytorch_1.1-py3.6              10ac12d6-6b30-4ccd-8392-3e922c096a92  base
tensorflow_1.15-py3.6-ddl      111e41b3-de2d-5422-a4d6-bf776828c4b7  base
autoai-kb_rt22.2-py3.10        125b6d9

##  Choose software specification

In [129]:
software_spec_uid = client.software_specifications.get_uid_by_name("runtime-22.1-py3.9")
software_spec_uid

'12b83a17-24d8-5082-900f-0ab31fbfd3cb'

In [130]:
import sklearn
sklearn.__version__

'1.0.2'

In [131]:
MODEL_NAME = 'Model Building'
DEPLOYMENT_NAME = 'space'
DEMO_MODEL = rf

In [135]:
model_props = {
    client.repository.ModelMetaNames.NAME: MODEL_NAME, 
    client.repository.ModelMetaNames.TYPE: 'scikit-learn_1.0', 
    client.repository.ModelMetaNames.SOFTWARE_SPEC_UID: software_spec_uid 
}

In [136]:
import json

In [137]:
model_details = client.repository.store_model(
    model=DEMO_MODEL, 
    meta_props=model_props, 
    training_data=train_x, 
    training_target=train_y
)

In [138]:
model_details

{'entity': {'hybrid_pipeline_software_specs': [],
  'label_column': 'Loan_Status',
  'schemas': {'input': [{'fields': [{'name': 'f0', 'type': 'float'},
      {'name': 'f1', 'type': 'float'},
      {'name': 'f2', 'type': 'float'},
      {'name': 'f3', 'type': 'float'},
      {'name': 'f4', 'type': 'float'},
      {'name': 'f5', 'type': 'float'},
      {'name': 'f6', 'type': 'float'},
      {'name': 'f7', 'type': 'float'},
      {'name': 'f8', 'type': 'float'},
      {'name': 'f9', 'type': 'float'},
      {'name': 'f10', 'type': 'float'}],
     'id': '1',
     'type': 'struct'}],
   'output': []},
  'software_spec': {'id': '12b83a17-24d8-5082-900f-0ab31fbfd3cb',
   'name': 'runtime-22.1-py3.9'},
  'type': 'scikit-learn_1.0'},
 'metadata': {'created_at': '2022-11-19T07:46:23.076Z',
  'id': '1f04b280-f2e1-4e63-9700-d230522fe297',
  'modified_at': '2022-11-19T07:46:47.418Z',
  'name': 'Model Building',
  'owner': 'IBMid-6640043Y2R',
  'resource_key': '7a380c52-42d2-42cc-b9d0-779ee01e8089',


In [139]:
model_id = client.repository.get_model_id(model_details)
model_id

'1f04b280-f2e1-4e63-9700-d230522fe297'

In [140]:
deployment_props = {
    client.deployments.ConfigurationMetaNames.NAME:DEPLOYMENT_NAME, 
    client.deployments.ConfigurationMetaNames.ONLINE: {}
}

In [141]:
deployment = client.deployments.create(
    artifact_uid=model_id, 
    meta_props=deployment_props 
)



#######################################################################################

Synchronous deployment creation for uid: '1f04b280-f2e1-4e63-9700-d230522fe297' started

#######################################################################################


initializing
Note: online_url is deprecated and will be removed in a future release. Use serving_urls instead.

ready


------------------------------------------------------------------------------------------------
Successfully finished deployment creation, deployment_uid='f223875c-d0df-46db-8796-a66030399dd1'
------------------------------------------------------------------------------------------------


