# Basic Python

## 1. Split this string

In [3]:
s = "Hi there Sam!"

In [4]:
print(s.split())

['Hi', 'there', 'Sam!']


*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [9]:
planet = "Earth"
diameter = 12742

In [11]:
print("The diameter of "+planet +" is "+str(diameter))

The diameter of Earth is 12742


## 3. In this nest dictionary grab the word "hello"

In [12]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [13]:
print(d["k1"][3]["tricky"][3]["target"][3]) 


hello


# Numpy

In [14]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [17]:
numpy = np.zeros(10)
numpy


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
array=np.ones(10)*5
print(array)


[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [20]:
import numpy as np
var2=np.arange(20,36,2)
var2


array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [21]:
np_matrix = np.arange(0,9).reshape(3,3) 
np_matrix


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [22]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a,b),axis=None)


array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [23]:
import pandas as pd
A = np.random.randint(10, size=(3,2))
df = pd.DataFrame(A,columns=['cola', 'colb'])
df

cola  colb
0     2     8
1     3     0
2     2     9

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [24]:
import pandas as pd
  
df = pd.DataFrame()
df['time'] = pd.date_range(start="1/1/2023",end="2/10/2023", freq ='24H')
df['year'] = df['time'].dt.year
df['month'] = df['time'].dt.month
df['day'] = df['time'].dt.day

df.head()


time  year  month  day
0 2023-01-01  2023      1    1
1 2023-01-02  2023      1    2
2 2023-01-03  2023      1    3
3 2023-01-04  2023      1    4
4 2023-01-05  2023      1    5

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [25]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(lists, columns =['col1',"col2","col3"]) 
df
 

col1 col2  col3
0     1  aaa    22
1     2  bbb    25
2     3  ccc    24