In [51]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MaxAbsScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score
from sklearn.metrics import f1_score
import pickle

In [52]:
scaler = MaxAbsScaler()

In [53]:
train = pd.read_csv('train.csv')

In [54]:
test = pd.read_csv('test.csv')

In [55]:
train.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        1           0          0              0             7933   
1       0        0           1          0              0             2600   
2       1        1           2          1              0             1993   
3       1        1           0          0              0             1828   
4       1        0           0          1              0             3598   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0         275               360               1   
1                  0         160               360               1   
2               1625         113               180               1   
3               1330         100               360               0   
4               1287         100               360               1   

   Property_Area  Loan_Status  
0              2            0  
1              2            0  
2              1            1  
3              2            0  
4              0            0

In [56]:
train_y = train.iloc[:,-1]

In [57]:
train_x = train.drop('Loan_Status',axis=1)

In [58]:
test_y = test.iloc[:,-1]

In [59]:
test_x = test.drop('Loan_Status',axis=1)

In [60]:
x = pd.concat([train_x,test_x],axis=0)
y = pd.concat([train_y,test_y],axis=0)

In [61]:
train_x = scaler.fit_transform(train_x)

In [62]:
test_x = scaler.fit_transform(test_x)

# DecisionTree

In [63]:
def decisionTree(train_x,test_x,train_y,test_y):
    dt = DecisionTreeClassifier()
    dt.fit(train_x,train_y)
    y_pred = dt.predict(test_x)
    print("**** Decision Tree Classifier ****")
    print('Confusion Matrix')
    print(confusion_matrix(test_y,y_pred))
    print('Classification Report')
    print(classification_report(test_y,y_pred))

# RandomForest

In [64]:
def randomForest(train_x,test_x,train_y,test_y):
    rf = RandomForestClassifier()
    rf.fit(train_x,train_y)
    y_pred = rf.predict(test_x)
    print("**** Random Forest Classifier ****")
    print('Confusion Matrix')
    print(confusion_matrix(test_y,y_pred))
    print('Classification Report')
    print(classification_report(test_y,y_pred))

# Knn

In [65]:
def knn(train_x,test_x,train_y,test_y):
    knn = KNeighborsClassifier()
    knn.fit(train_x,train_y)
    y_pred = knn.predict(test_x)
    print("**** KNeighbour Classifier ****")
    print('Confusion Matrix')
    print(confusion_matrix(test_y,y_pred))
    print('Classification Report')
    print(classification_report(test_y,y_pred))

# xgboost

In [66]:
def xgboost(train_x,test_x,train_y,test_y):
    xg = GradientBoostingClassifier()
    xg.fit(train_x,train_y)
    y_pred = xg.predict(test_x)
    print("**** Gradient Boosting Classifier ****")
    print('Confusion Matrix')
    print(confusion_matrix(test_y,y_pred))
    print('Classification Report')
    print(classification_report(test_y,y_pred))

# Comparing The Models

In [67]:
decisionTree(train_x,test_x,train_y,test_y)

**** Decision Tree Classifier ****
Confusion Matrix
[[63 31]
 [49 86]]
Classification Report
              precision    recall  f1-score   support

           0       0.56      0.67      0.61        94
           1       0.74      0.64      0.68       135

    accuracy                           0.65       229
   macro avg       0.65      0.65      0.65       229
weighted avg       0.66      0.65      0.65       229



In [68]:
randomForest(train_x,test_x,train_y,test_y)

**** Random Forest Classifier ****
Confusion Matrix
[[ 65  29]
 [ 27 108]]
Classification Report
              precision    recall  f1-score   support

           0       0.71      0.69      0.70        94
           1       0.79      0.80      0.79       135

    accuracy                           0.76       229
   macro avg       0.75      0.75      0.75       229
weighted avg       0.75      0.76      0.76       229



In [69]:
knn(train_x,test_x,train_y,test_y)

**** KNeighbour Classifier ****
Confusion Matrix
[[ 62  32]
 [ 25 110]]
Classification Report
              precision    recall  f1-score   support

           0       0.71      0.66      0.69        94
           1       0.77      0.81      0.79       135

    accuracy                           0.75       229
   macro avg       0.74      0.74      0.74       229
weighted avg       0.75      0.75      0.75       229



C:\Users\CHANDRU\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [70]:
xgboost(train_x,test_x,train_y,test_y)

**** Gradient Boosting Classifier ****
Confusion Matrix
[[63 31]
 [36 99]]
Classification Report
              precision    recall  f1-score   support

           0       0.64      0.67      0.65        94
           1       0.76      0.73      0.75       135

    accuracy                           0.71       229
   macro avg       0.70      0.70      0.70       229
weighted avg       0.71      0.71      0.71       229



In [71]:
rf = RandomForestClassifier()
rf.fit(train_x,train_y)
ypred = rf.predict(test_x)

In [72]:
f1_score(ypred,test_y,average='weighted')

0.7691638468931046

In [73]:
cv = cross_val_score(rf,x,y,cv=5)

In [74]:
np.mean(cv)

0.812146804295694

In [75]:
import joblib
joblib.dump(rf,'model.pkl')

['model.pkl']